name: homepick_print
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # printing: ^5.2.1
  provider: ^5.0.0
  path_provider: ^2.0.1
  open_file: ^3.2.1
  msix: ^2.1.1
  mailer: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/html/
    - assets/keys/
    - packages/homepick_print/assets/img/certificate-10y.jpeg
    - packages/homepick_print/assets/img/certificate-15y.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

msix_config:
  display_name: HomePickPrint
  publisher_display_name: Tronisys
  identity_name: Tronisys.Printing.HomePickPrint
  msix_version: 1.0.0.0
  certificate_path: CERTIFICATE.pfx
  certificate_password: caucasus042
  publisher: E = info@tronisys.com, CN = Tronisys, OU = Development, O = Tronisys, L = Lahore, S = Punjab, C = PK
  logo_path: assets/img/homepick-logo.png
  start_menu_icon_path: assets/img/homepick-logo.png
  tile_icon_path: assets/img/homepick-logo.png
  icons_background_color: transparent
  architecture: x64
  capabilities: 'allJoyn,codeGeneration,voipCall,removableStorage,musicLibrary,enterpriseAuthentication,spatialPerception,remoteSystem,userNotificationListener,backgroundMediaPlayback,videosLibrary,picturesLibrary,userDataTasks,globalMediaControl,systemManagement,documentsLibrary,accessoryManager'